services:

  mongo:
    container_name: action-labs-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - carbon-calc

networks:
  carbon-calc:
    driver: bridge

volumes:
  mongodb_data: